<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="0" ignored="0" total="1" passed="1">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="826" started-at="2019-06-26T11:44:07Z" finished-at="2019-06-26T11:44:07Z">
    <groups>
    </groups>
    <test name="Default test" duration-ms="826" started-at="2019-06-26T11:44:07Z" finished-at="2019-06-26T11:44:07Z">
      <class name="com.qa.test.CancelOrder">
        <test-method status="PASS" signature="Setup()[pri:0, instance:com.qa.test.CancelOrder@5e3a8624]" name="Setup" is-config="true" duration-ms="9" started-at="2019-06-26T11:44:07Z" finished-at="2019-06-26T11:44:07Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Setup -->
        <test-method status="PASS" signature="PUTAPITAKEORDER()[pri:1, instance:com.qa.test.CancelOrder@5e3a8624]" name="PUTAPITAKEORDER" duration-ms="798" started-at="2019-06-26T11:44:07Z" finished-at="2019-06-26T11:44:07Z">
          <exception class="org.json.JSONException">
            <message>
              <![CDATA[JSONObject["status"] not found.]]>
            </message>
            <full-stacktrace>
              <![CDATA[org.json.JSONException: JSONObject["status"] not found.
at org.json.JSONObject.get(JSONObject.java:566)
at com.qa.util.TestUtil.getValueByJPath(TestUtil.java:13)
at com.qa.test.CancelOrder.PUTAPITAKEORDER(CancelOrder.java:87)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- org.json.JSONException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- PUTAPITAKEORDER -->
      </class> <!-- com.qa.test.CancelOrder -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
